from datetime import timedelta
import os

# BBs are left, top, right, bottom
MPS_DAY_NIGHT_BUTTON_COORD = (700, 20)  # x, y
MPS_DAY_NIGHT_BUTTON_BB = (
    MPS_DAY_NIGHT_BUTTON_COORD[0],
    MPS_DAY_NIGHT_BUTTON_COORD[1],
    MPS_DAY_NIGHT_BUTTON_COORD[0] + 1,
    MPS_DAY_NIGHT_BUTTON_COORD[1] + 1,
)
MPS_DAY_NIGHT_BUTTON_HEX = ""
MPS_DAY_NIGHT_BACKGROUND_BB = (1, 1, 1, 1)
MPS_DAY_NIGHT_BUTTON_DAY_HEX = "#FFFFFF"
MPS_DAY_NIGHT_BUTTON_NIGHT_HEX = "#000000"

TIME_BETWEEN_GLOBAL_MESSAGE = timedelta(hours=1)

PIXEL_CLICKER_DISCORD_WEBHOOK = os.environ["PIXEL_CLICKER_DISCORD_WEBHOOK"]
